//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KERMESSE_MYGRO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_tasacambio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_tasacambio()
        {
            this.tbl_tasacambio_det = new HashSet<tbl_tasacambio_det>();
        }

        public int id_tasacambio { get; set; }

        [Display(Name = "Moneda de origen: ")]
        [Required(ErrorMessage = "Asigne una moneda")]
        public int id_monedaO { get; set; }

        [Display(Name = "Moneda de cambio: ")]
        [Required(ErrorMessage = "Asigne una moneda")]
        public int id_monedaC { get; set; }

        [Display(Name = "Mes: ")]
        [Required(ErrorMessage = "Seleccione un mes")]
        public int mes { get; set; }

        [Display(Name = "Año: ")]
        [Required(ErrorMessage = "Seleccione un año")]
        public int anio { get; set; }
        public int estado { get; set; }

        public virtual tbl_moneda tbl_moneda { get; set; }
        public virtual tbl_moneda tbl_moneda1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_tasacambio_det> tbl_tasacambio_det { get; set; }
    }
}
