//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KERMESSE_MYGRO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_arqueocaja_det
    {
        public int id_arqueocaja_det { get; set; }
        public int id_arqueocaja { get; set; }
        public int id_moneda { get; set; }
        public int id_denominacion { get; set; }
        public decimal cantidad { get; set; }
        public decimal subtotal { get; set; }
    
        public virtual tbl_arqueocaja tbl_arqueocaja { get; set; }
        public virtual tbl_denominacion tbl_denominacion { get; set; }
        public virtual tbl_moneda tbl_moneda { get; set; }
    }
}
