//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KERMESSE_MYGRO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ingresocom_det
    {
        public int id_ingresocom_det { get; set; }
        public int id_ingresocom { get; set; }
        public int id_bono { get; set; }
        public string denominacion { get; set; }
        public int cantidad { get; set; }
        public decimal subtotal { get; set; }
    
        public virtual tbl_bonos tbl_bonos { get; set; }
        public virtual tbl_ingreso_com tbl_ingreso_com { get; set; }
    }
}
