//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KERMESSE_MYGRO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_arqueocajadet
    {
        public int id_ArqueoCaja { get; set; }
        public string nombre { get; set; }
        public string valor { get; set; }
        public decimal cantidad { get; set; }
        public string subtotal { get; set; }
    }
}
