//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KERMESSE_MYGRO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_denominacion
    {
        public int id_Denominacion { get; set; }
        public string nombre { get; set; }
        public decimal valor { get; set; }
        public string valor_letras { get; set; }
        public string equivalente { get; set; }
    }
}
