//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KERMESSE_MYGRO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ingresocomdet
    {
        public int id_ingreso_comunidad_det { get; set; }
        public int Id_ingresoM { get; set; }
        public string Bono { get; set; }
        public string Denominacion { get; set; }
        public int Cantidad { get; set; }
        public decimal Subtotal { get; set; }
    }
}
