//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KERMESSE_MYGRO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ingresoscom
    {
        public int id_ingreso_comunidad { get; set; }
        public string Kermesse { get; set; }
        public string Comunidad { get; set; }
        public string Responsable_com { get; set; }
        public string Producto { get; set; }
        public int Cantidad_disponible { get; set; }
        public int Cantidad_vendida { get; set; }
        public int Total_Bonos { get; set; }
    }
}
