//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KERMESSE_MYGRO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Precios
    {
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public decimal precio_venta { get; set; }
        public string Kermesse { get; set; }
        public int id_listaprecio_det { get; set; }
    }
}
