//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KERMESSE_MYGRO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_tasacambiodet
    {
        public int id_tasaCambio { get; set; }
        public string tasa { get; set; }
        public System.DateTime fecha { get; set; }
        public string tipoCambio { get; set; }
    }
}
