//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KERMESSE_MYGRO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_tasacambio
    {
        public int id_tasaCambio { get; set; }
        public string original { get; set; }
        public string cambio { get; set; }
        public int mes { get; set; }
        public int anio { get; set; }
    }
}
